# PDF++ CE does not take donations. These point to the original author of PDF++,
# who wrote essentially all of this code.
github: RyotaUshio
custom: ['https://www.buymeacoffee.com/ryotaushio']
ko_fi: ryotaushio
